services:
  - type: web
    name: oshoai
    env: python
    buildCommand: pip install -r requirements.txt; python manage.py collectstatic --noinput
    startCommand: gunicorn oshochatbot.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120
    healthCheckPath: /healthz/
    autoDeploy: true
